### ISSUE TITLE
Variant map not loading

### ISSUE THREAD

**Issue by pwh124** [kircherlab/MPRA_SaturationMutagenesis#7]
Hello,

I think this website is a wonderful resource and I appreciate the effort that went into making it. As I browsed around the site, I kept running into the same error when trying to visualize the variant map:
<img width="1007" alt="Screen Shot 2019-09-16 at 4 24 24 PM" src="https://user-images.githubusercontent.com/7634060/64990909-c4d16380-d89e-11e9-8e0e-abd3dcb695f2.png">

I am not sure if this is an issue on my end or on the app's end. Again thanks for the resource!

Paul

**Comment by visze** [comment]
Hi Paul,

thank you for your ticket. We can reproduce this issue. It is definitely not a problem on your side. I have to debug it more carefully. Maybe it is a server issue (memory overflow) or a code issue.

Best,
Max

**Comment by visze** [comment]
Hey Paul,

can you check again if you still have that issue?

Best,
Max

**Comment by pwh124** [comment]
Hi Max,

I clicked on most the promoters and about half of the enhancers. 

All loaded great!

Thanks again for the great resource!

Paul
